# Generated by Django 4.1.3 on 2023-01-25 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_order_checkout_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='checkout_session',
            new_name='checkout_session_id',
        ),
    ]
