# Generated by Django 4.1.3 on 2023-01-28 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_faqs_second_faq_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqs',
            name='second_faq_id',
        ),
    ]
