# Generated by Django 4.1.3 on 2023-01-28 07:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_remove_faqs_second_faq_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
