# Generated by Django 4.1.3 on 2023-01-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_order_cep_alter_order_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracker',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
