# Generated by Django 4.1.3 on 2023-01-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complement',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
