# Generated by Django 4.1.3 on 2023-01-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_assessment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='image',
            field=models.ImageField(blank=True, upload_to='user/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
