# Generated by Django 4.1.3 on 2023-01-11 21:57

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_assessment_image_assessment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='image',
            field=models.ImageField(blank=True, upload_to='procfile/%Y/%m/%d'),
        ),
    ]
