# Generated by Django 4.1.3 on 2023-01-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_assessment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='choice_nota',
            field=models.CharField(choices=[('péssimo', 'péssimo'), ('ruim', 'ruim'), ('bom', 'bom'), ('excelente', 'excelente'), ('maravilhoso', 'maravilhoso')], default='ruim', max_length=12),
        ),
    ]
